import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PageBody from './components/PageBody'

export const metadata: Metadata = {
	title: 'Ark-House',
	description: 'Generated by create next app',
	creator: 'ustymenko.denys@gmail.com',
}

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={`${inter.variable} font-sans overflow-x-clip h-fit`}>
			<head>
				<meta
					name='next-size-adjust'
					content='auto'
				/>
			</head>
			<PageBody>{children}</PageBody>
		</html>
	)
}
