query Showcase {
	progects(filters: { showcase: { eq: true } }) {
		title
		location
		media {
			alternativeText
			url
			width
			height
		}
		info {
			label
			value
		}
		description
		gallery {
			title
			location
			media {
				alternativeText
				url
				width
				height
			}
		}
	}
}
